  
version: '3'
services:
 node:
    build: .
    volumes:
      - ./src:${PATH_TO_APP}
      - ./src/resources/middleware/logs:${PATH_TO_LOGS}
      - my-app:${PATH_TO_APP}
      - my-app-log:${PATH_TO_LOGS}
    ports:
      - ${PORT}:${APP_PORT}
    networks:
      - app
    depends_on:
      - postgres
    environment:
      - PATH_TO_APP=${PATH_TO_APP}
      - PATH_TO_LOGS=${PATH_TO_LOGS}
      - PORT=${PORT}
      - APP_PORT=${APP_PORT}
    restart: always


 postgres:
    build: ./database/
    volumes:
      - data-volume:/var/lib/postgresql/data
    ports:
      - ${POSGRES_PORT}:${POSTGRES_PORT}
    environment:
      APP_PORT: ${APP_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSGRES_PORT: ${POSGRES_PORT}
    networks:
      - app
    restart: always

networks:
  app: 
    driver: bridge

volumes: 
  my-app:
  my-app-log:
  data-volume: 