  
version: '3'
services:
 node:
    build: .
    volumes:
  - ./src/resources/middleware/logs/:/usr/app/logs/
  - ./:/usr/app/ 
      build: .
      container_name: 'node'
      networks: 
        - app
    ports:
      - ${PORT}:${PORT}
    networks:
      - app
    depends_on:
      - postgres
    environment:
      - ${PORT}:${PORT}
    restart: always
 postgres:
    build: ./database/
    volumes:
    - ./database/:/usr/app/database/
    - ./migration/:/usr/app/migration/
    ports:
      - ${POSTGRES_OUTPUT_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSGRES_PORT: ${POSTGRES_PORT}
    networks:
      - app
    restart: always

networks:
  app: 
    driver: bridge